# This is not the final version of the group just using approach 1 in this design doc - https://soloio.slab.com/posts/portal-user-authentication-authorization-design-doc-75w10xtj#hjlt7-proposed-approach-1-define-which-usage-plans-a-group-has-access-to-in-the-group-cr
# for this use case
apiVersion: apimanagement.gloo.solo.io/v2
kind: Group
metadata:
  name: customers
  namespace: gloo-mesh
labels:
  portal: sample-bank-portal
spec:
  name: partner-group
  description: a group for users accessing the partner APIs
  # These will be matched against the value of the group claim in the id_token
  groupNames:
  - customers
  # access level defines which APIs the user can view
  # while usage plans will indicate which usage plans
  # users belonging to this group can create API keys for
  accessLevel:
    apis:
    - routeTable:
        labels:
          customers-group: true
    usagePlans:
    - name: bronze
    - name: silver
    - name: gold