apiVersion: apimanagement.gloo.solo.io/v2
kind: Portal
metadata:
  name: sample-bank-portal
  namespace: gloo-mesh
spec:
  domains:
  - "bank.portal.io"
  portalBackendSelector:
  - selector:
      namespace: gloo-mesh
      cluster: cluster-1
  usagePlans:
  - name: bronze
    displayName: "Bronze Plan"
    description: "A basic usage plan"
  - name: silver
    displayName: "Silver Plan"
    description: "A better usage plan"
  - name: gold
    displayName: "Gold Plan"
    description: "The best usage plan!"
  # Visibility setting for the APIs in the portal
  visibility:
    public: false # can be omitted as it defaults to false if not set
    privateAPILabels:
      - portal-visibility: private
  apis:
  - routeTable:
      labels:
      - portal: sample-bank-portal
  groupClaimKey: groups
