apiVersion: security.policy.gloo.solo.io/v2
kind: ExtAuthPolicy
metadata:
  name: portal-oidc-auth
  namespace: gloo-mesh
spec:
  applyToRoutes:
  - route:
      labels:
        oauth: "true"
  config:
    server:
      name: ext-auth-server
      namespace: gloo-mesh-addons
      cluster: cluster-1
    glooAuth:
      configs:
      - oauth2:
          oidcAuthorizationCode:
            appUrl: bank.portal.io
            callbackPath: /callback
            clientId: ${CLIENT_ID}
            clientSecretRef:
              name: oauth
              namespace: gloo-mesh
            issuerUrl: ${KEYCLOAK_URL}/auth/realms/master/
            scopes:
            - email
            session:
              failOnFetchFailure: true
              cookie:
                allowRefreshing: true
              cookieOptions:
                notSecure: true
                maxAge: 3600
            headers:
              idTokenHeader: jwt