# Configuring this resource is not a Portal Admin responsibility 
apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
 name: partner-registration-api-rt
 namespace: istio-gateway-ns
labels:
  portal: sample-bank-portal
  customers-group: true
  partners-group: true
spec:
  hosts:
    - "bank.io"
  defaultDestination:
    port:
      number: 9080
    ref:
      name: partner-registration-api
      namespace: partners
      cluster: cluster-1
  virtualGateways:
    - name: north-south-gw